#!/bin/bash
# Finding 3 with --force: the lane folder goes, so a user-edited AGENTS.md must be rescued, while a purely
# generated one may be dropped.
. "$(dirname "$0")/common.sh" "$@"
APP=$(remote app)
work clone "$APP" w >/dev/null 2>&1
W=$ROOT/tries/w
CWD=$W/app work lane ui >/dev/null 2>&1
CWD=$W/app work lane gen >/dev/null 2>&1
mkdir -p "$W/ui" "$W/gen"
git -C "$W/app@ui" worktree move "$W/app@ui" "$W/ui/app" >/dev/null
git -C "$W/app@gen" worktree move "$W/app@gen" "$W/gen/app" >/dev/null
printf '<!-- work:begin (generated by `work`, edits inside are overwritten) -->\ngen\n<!-- work:end -->\nMY LANE NOTES\n' > "$W/ui/AGENTS.md"
printf '<!-- work:begin (generated by `work`, edits inside are overwritten) -->\ngen\n<!-- work:end -->\n' > "$W/gen/AGENTS.md"
echo "@AGENTS.md" > "$W/gen/CLAUDE.md"
work migrate w --force 2>&1 | tail -3
echo "workspace: $(ls "$W" | tr '\n' ' ')"
RESCUED=$(grep -rl "MY LANE NOTES" "$W" 2>/dev/null | head -1)
if [ -z "$RESCUED" ]; then verdict "FINDING 3 (--force) PRESENT (the user's text was deleted)"
elif [ -e "$W/ui" ] || [ -e "$W/gen" ]; then verdict "FINDING 3 (--force) PRESENT (a lane folder survived --force)"
else verdict "FINDING 3 (--force) FIXED (edited file kept as ${RESCUED#$W/}, generated ones dropped with their folders)"; fi
