import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { repoBranch, topoLanes, type WorkspaceModel } from "./model.ts";
import { worktreeDir } from "./naming.ts";
import type { Root } from "./root.ts";

const BEGIN = "<!-- work:begin (generated by `work`, edits inside are overwritten) -->";
const END = "<!-- work:end -->";
const BLOCK = /<!-- work:begin[^>]*-->[\s\S]*?<!-- work:end -->/;

function upsertBlock(file: string, body: string): void {
  const block = `${BEGIN}\n${body.trimEnd()}\n${END}`;
  const old = existsSync(file) ? readFileSync(file, "utf8") : "";
  const next = BLOCK.test(old) ? old.replace(BLOCK, block) : old ? `${block}\n\n${old}` : `${block}\n`;
  if (next !== old) writeFileSync(file, next);
}

function ensureClaudeMd(dir: string): void {
  const file = join(dir, "CLAUDE.md");
  if (!existsSync(file)) writeFileSync(file, "@AGENTS.md\n");
}

export function workspaceAgentsBody(workspaceName: string, space: string, model: WorkspaceModel): string {
  const lanes = topoLanes(model);
  const rows = lanes.map((name) => {
    const l = model.lanes[name]!;
    const repos = Object.keys(l.repos).sort();
    const folders = repos.map((r) => `\`${worktreeDir(name, r)}/\`${repoBranch(l, r) === l.branch ? "" : ` (${repoBranch(l, r)})`}`);
    return `| \`${name}\` | \`${l.branch}\` | ${l.parent ?? "trunk"} | ${folders.join(", ") || "–"} |`;
  });
  const example = lanes.flatMap((name) => Object.keys(model.lanes[name]!.repos).map((r) => worktreeDir(name, r)))[0];
  return [
    `# Workspace \`${workspaceName}\` (space \`${space}\`)`,
    "",
    "Managed by `work`. Each lane is one feature on one branch, worked on by one agent. Lanes can stack on",
    "each other; a repo in a lane is based on the nearest ancestor lane that has the same repo, else on trunk.",
    "A lane is not a folder: its worktrees sit here as `<repo>` (lane `root`) or `<repo>@<lane>`.",
    "",
    "| Lane | Branch | Stacked on | Folders |",
    "|---|---|---|---|",
    ...rows,
    "",
    "Rules for agents:",
    `- Work only in your own lane's folders${example ? ` (\`${example}\`, …)` : ""}; the other folders belong to other agents.`,
    "- Commit on the lane's branch; never switch branches inside a worktree.",
    "- `work info --json` shows lanes, branches and status; `work sync` restacks lanes onto their parents;",
    "  `work submit` pushes and opens/updates one PR per repo and lane.",
    "- New stacked feature: `work lane <name> [repos…] --on <lane>` (prints the new worktrees).",
  ].join("\n");
}

/** Write/refresh the workspace's AGENTS.md (+ CLAUDE.md importing it); worktrees never get one. */
export function writeAgentFiles(root: Root, workspacePath: string, model: WorkspaceModel): void {
  if (!Object.keys(model.lanes).length) return;
  const workspaceName = basename(workspacePath);
  const space = basename(dirname(workspacePath));
  upsertBlock(join(workspacePath, "AGENTS.md"), workspaceAgentsBody(workspaceName, space, model));
  ensureClaudeMd(workspacePath);
  void root;
}
