import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { childrenOf, type EntryModel, repoBranch, topoLanes } from "./model.ts";
import type { Root } from "./root.ts";

const BEGIN = "<!-- work:begin (generated by `work`, edits inside are overwritten) -->";
const END = "<!-- work:end -->";
const BLOCK = /<!-- work:begin[^>]*-->[\s\S]*?<!-- work:end -->/;

function upsertBlock(file: string, body: string): void {
  const block = `${BEGIN}\n${body.trimEnd()}\n${END}`;
  const old = existsSync(file) ? readFileSync(file, "utf8") : "";
  const next = BLOCK.test(old) ? old.replace(BLOCK, block) : old ? `${block}\n\n${old}` : `${block}\n`;
  if (next !== old) writeFileSync(file, next);
}

function ensureClaudeMd(dir: string): void {
  const file = join(dir, "CLAUDE.md");
  if (!existsSync(file)) writeFileSync(file, "@AGENTS.md\n");
}

function parentLabel(model: EntryModel, lane: string): string {
  const p = model.lanes[lane]!.parent;
  return p ? `lane \`${p}\` (branch \`${model.lanes[p]?.branch ?? "?"}\`)` : "trunk (`origin/HEAD`)";
}

export function entryAgentsBody(entryName: string, space: string, model: EntryModel): string {
  const rows = topoLanes(model).map((name) => {
    const l = model.lanes[name]!;
    const repos = Object.keys(l.repos).sort().map((r) => (repoBranch(l, r) === l.branch ? r : `${r} (${repoBranch(l, r)})`));
    return `| \`${name}/\` | \`${l.branch}\` | ${l.parent ?? "trunk"} | ${repos.join(", ") || "–"} |`;
  });
  return [
    `# Workspace \`${entryName}\` (space \`${space}\`)`,
    "",
    "Managed by `work`. Each lane is one feature on one branch, worked on by one agent. Lanes can stack on",
    "each other; a repo in a lane is based on the nearest ancestor lane that has the same repo, else on trunk.",
    "",
    "| Lane | Branch | Stacked on | Repos |",
    "|---|---|---|---|",
    ...rows,
    "",
    "Rules for agents:",
    "- Work only inside your own lane folder. Other lanes belong to other agents.",
    "- Commit on the lane's branch; never switch branches inside a checkout.",
    "- `work info --json` shows lanes, branches and status; `work sync` restacks lanes onto their parents;",
    "  `work submit` pushes and opens/updates one PR per repo and lane.",
    "- New stacked feature: `work lane <name> [repos…] --on <lane>` (prints the new lane path).",
  ].join("\n");
}

export function laneAgentsBody(entryName: string, model: EntryModel, lane: string): string {
  const l = model.lanes[lane]!;
  const siblings = Object.keys(model.lanes).filter((n) => n !== lane).sort();
  const children = childrenOf(model, lane);
  const repos = Object.keys(l.repos).sort();
  return [
    `# Lane \`${lane}\` of workspace \`${entryName}\``,
    "",
    `- Branch: \`${l.branch}\`${repos.some((r) => repoBranch(l, r) !== l.branch) ? " (some repos differ, see below)" : ""}`,
    `- Stacked on: ${parentLabel(model, lane)}`,
    `- Repos: ${repos.map((r) => `\`${r}/\`${repoBranch(l, r) !== l.branch ? ` on \`${repoBranch(l, r)}\`` : ""}`).join(", ") || "none yet (`work add <repo>`)"}`,
    children.length ? `- Lanes stacked on this one: ${children.join(", ")} — they are rebased onto your branch by \`work sync\`.` : "",
    siblings.length ? `- Other lanes (off-limits): ${siblings.join(", ")}` : "",
    "",
    "Stay inside this folder. Commit on the lane branch. Run `work sync` when the parent lane changed and",
    "`work submit` to push and open/update PRs.",
  ]
    .filter((l, i, a) => l !== "" || a[i - 1] !== "")
    .join("\n");
}

/** Write/refresh AGENTS.md (+ CLAUDE.md importing it) for the entry and each lane. */
export function writeAgentFiles(root: Root, entryPath: string, model: EntryModel): void {
  if (!Object.keys(model.lanes).length) return;
  const entryName = basename(entryPath);
  const space = basename(dirname(entryPath));
  upsertBlock(join(entryPath, "AGENTS.md"), entryAgentsBody(entryName, space, model));
  ensureClaudeMd(entryPath);
  for (const lane of Object.keys(model.lanes)) {
    const dir = join(entryPath, lane);
    if (!existsSync(dir)) continue;
    upsertBlock(join(dir, "AGENTS.md"), laneAgentsBody(entryName, model, lane));
    ensureClaudeMd(dir);
  }
  void root;
}
